name: 'actions-license-check'
description: 'Action to check the repo for (production) dependencies that have an disallowed license'
author: 'tangro'
inputs:
  allowed-licenses:
    description: 'The list of allowed licenses. Use semicolons to separate licenses.'
    required: false
    default: 'MIT; Apache-2.0; ISC; Custom: https://www.telerik.com/kendo-angular-ui/; BSD'
runs:
  using: 'node12'
  main: 'dist/index.js'
